apiVersion: apps/v1
kind: Deployment
metadata:
  name: sitas-downloaders-soundcloud
  namespace: sitas
spec:
  selector:
    matchLabels:
      app: sitas-downloaders-soundcloud
  template:
    metadata:
      labels:
        app: sitas-downloaders-soundcloud
    spec:
      containers:
        - name: sitas-downloaders-soundcloud
          image: oscarvicente/sitas-downloaders-soundcloud-prod
          resources:
            limits:
              memory: 1Gi
              cpu: 1
          env: 
            - name: AZURE_SERVICE_BUS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: sitas-downloaders-soundcloud-secret
                  key: AZURE_SERVICE_BUS_CONNECTION_STRING
            - name: AZURE_SERVICE_BUS_DOWNLOAD_REQUEST_QUEUE
              value: download-request-dev-prod
            - name: AZURE_SERVICE_BUS_DOWNLOAD_REQUEST_SOUNDCLOUD_QUEUE
              value: download-request-soundcloud-prod
            - name: AZURE_SERVICE_BUS_DOWNLOAD_COMPLETED_QUEUE
              value: download-completed-prod
            - name: MINIO_INTERNAL_ENDPOINT
              value: oscarvx00.ddns.net
            - name: MINIO_INTERNAL_PORT
              value: "10000"
            - name: MINIO_INTERNAL_USER
              valueFrom:
                secretKeyRef:
                  name: sitas-downloaders-soundcloud-secret
                  key: MINIO_INTERNAL_USER
            - name: MINIO_INTERNAL_PASS
              valueFrom:
                secretKeyRef:
                  name: sitas-downloaders-soundcloud-secret
                  key: MINIO_INTERNAL_PASS
            - name: MINIO_INTERNAL_BUCKET
              value: internal-storage-prod
            - name: SOUNDCLOUD_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: sitas-downloaders-soundcloud-secret
                  key: SOUNDCLOUD_CLIENT_ID